// 3 种敌人 + 6 Boss（含终极混合）

export const ENEMY_KIND = {
  NORMAL: 'normal',
  FLYING: 'flying',
  STEALTH: 'stealth',
};

export const ENEMY_DEFS = {
  [ENEMY_KIND.NORMAL]: {
    name: '步兵',
    color: '#94a3b8',
    hp: 30,
    speed: 60,
    reward: 5,
    bounty: 5,
    size: 12,
    icon: 'soldier',
    flying: false,
    stealth: false,
  },
  [ENEMY_KIND.FLYING]: {
    name: '飞龙',
    color: '#38bdf8',
    hp: 20,
    speed: 85,
    reward: 8,
    bounty: 8,
    size: 12,
    icon: 'dragon',
    flying: true,
    stealth: false,
    floatY: 24,
  },
  [ENEMY_KIND.STEALTH]: {
    name: '幽影',
    color: '#a78bfa',
    hp: 45,
    speed: 50,
    reward: 12,
    bounty: 12,
    size: 12,
    icon: 'ghost',
    flying: false,
    stealth: true,
    alpha: 0.25,
  },
};

export const BOSS_DEFS = [
  {
    kind: 'bossDragon',
    name: '飞龙母舰',
    color: '#0ea5e9',
    hp: 600,
    speed: 40,
    size: 22,
    reward: 150,
    flying: true,
    stealth: false,
    summonInterval: 8000,
    summonKind: ENEMY_KIND.FLYING,
    summonCount: 2,
  },
  {
    kind: 'bossGhost',
    name: '幽影领主',
    color: '#8b5cf6',
    hp: 720,
    speed: 38,
    size: 22,
    reward: 180,
    flying: false,
    stealth: false,
    summonInterval: 7000,
    summonKind: ENEMY_KIND.STEALTH,
    summonCount: 3,
  },
  {
    kind: 'bossGolem',
    name: '钢铁巨像',
    color: '#64748b',
    hp: 900,
    speed: 32,
    size: 26,
    reward: 220,
    flying: false,
    stealth: false,
    armor: { preSeconds: 5, mult: 0.5 },
  },
  {
    kind: 'bossPhantom',
    name: '幽能龙',
    color: '#22d3ee',
    hp: 1050,
    speed: 46,
    size: 23,
    reward: 260,
    flying: true,
    stealth: false,
    floatY: 26,
    // 相位隐匿：每 7s 隐身 2.4s，期间只有反隐塔能锁定
    stealthCycle: { period: 7000, hiddenMs: 2400 },
    summonInterval: 9000,
    summonKind: ENEMY_KIND.FLYING,
    summonCount: 2,
  },
  {
    kind: 'bossShadow',
    name: '暗影领主',
    color: '#7c3aed',
    hp: 1150,
    speed: 42,
    size: 25,
    reward: 280,
    flying: false,
    stealth: false,
    // 相位隐匿：每 6s 隐身 2.2s
    stealthCycle: { period: 6000, hiddenMs: 2200 },
    summonInterval: 9000,
    summonGroups: [
      { kind: ENEMY_KIND.NORMAL, count: 2 },
      { kind: ENEMY_KIND.FLYING, count: 2 },
      { kind: ENEMY_KIND.STEALTH, count: 2 },
    ],
  },
  {
    kind: 'bossMix',
    name: '终极混合',
    color: '#ec4899',
    hp: 1200,
    speed: 50,
    size: 24,
    reward: 300,
    flying: true,
    stealth: true,
    summonInterval: 6000,
    summonKind: ENEMY_KIND.NORMAL,
    summonCount: 4,
  },
];