export default {
  name: '02.杂项整理',
  topping: false, // 是否置顶
  children: [
    { name: '99.vben-admin中的Authority.md' },
    { name: '98.vben-admin自定义表单.md' },
    { name: '97.vben-admin异步组件加载方法封装.md' },
    { name: '96.imgurlToBase64.md' },
    { name: '95.base64ToBlob.md' },
    { name: '94.vben-admin监听dom元素的宽高变化.md' },
    { name: '93.vben-admin中动态添加路由.md' },
    { name: '92.vben-admin中的useTitle.md' },
    { name: '91.vben-admin中的useScript.md' },
    { name: '90.vben-admin中的usePermission.md' },
    { name: '89.vben-admin中的usePagination.md' },
    { name: '88.vben-admin中的useFullContent.md' },
    { name: '87.vben-admin中的useECharts.md' },
    { name: '86.vben-admin中的useCopyToClipboard.md' },
    { name: '85.vben-admin中的useContextMenu.md' },
    { name: '84.vben-admin中的useContentHeight.md' },
    { name: '83.vben-admin中setting中的usehook.md' },
    { name: '82.vben-admin中useScroll.md' },
    { name: '81.vben-admin中useBreakpoint.md' },
    { name: '80.vben-admin中usePageContext.md' },
    { name: '79.vben-admin中useFormItem.md' },
    { name: '78.vben-admin中useWindowSizeFn.md' },
    { name: '77.vben-admin中useScrollTo.md' },
    { name: '76.vben-admin中useRefs.md' },
    { name: '75.vben-admin中useAttrs.md' },
    { name: '74.vben-admin中onMountedOrActivated.md' },
    { name: '73.vue顶层async.md' },
    { name: '72.threejs内存管理.md' },
    { name: '71.node切换版本.md' },
    { name: '70.vue3+ts中如何指定类型.md' },
    { name: '69.微信蓝牙使用.md' },
    { name: '68.jsBridge与App交互.md' },
    { name: '67.理解vue3里effectScope.md' },
    { name: '66.安卓与ios时间有关bug.md' },
    { name: '65.父组件插槽透传.md' },
    { name: '64.循环Promise链式调用.md' },
    { name: '63.vue中的createApp与h与render与mount.md' },
    { name: '62.无感刷新token.md' },
    { name: '61.项目中如何安装同一依赖的两个版本.md' },
    { name: '60.vue底层相关补漏.md' },
    { name: '59.一个艾特@功能.md' },
    { name: '58.vant的lazyload.md' },
    { name: '57.node文件操作.md' },
    { name: '56.gsap滚动条动画.md' },
    { name: '55.unipp-vue3环境配置.md' },
    { name: '54.live2d在vue中引用.md' },
    { name: '53.压缩图片.md' },
    { name: '52.uni-app如何实现路由拦截.md' },
    { name: '51.Vue模式环境配置.md' },
    { name: '50.微信公众号网页授权.md' },
    { name: '49.uniapp中nvue相关.md' },
    { name: '48.Vue3响应式原理以及依赖模型解析.md' },
    { name: '47.计算字符串宽度.md' },
    { name: '46.解析url参数.md' },
    { name: '45.移动端H5自动播放视频.md' },
    { name: '44.小溜一下字符串方法.md' },
    { name: '43.时间复杂度与空间复杂度.md' },
    { name: '42.函数式编程.md' },
    { name: '41.git修改commit信息.md' },
    { name: '40.vue3的一个toast组件.md' },
    { name: '39.vue3的effectScope.md' },
    {
      name: '01.css视差demo',
      link: 'https://github.com/a1392558812/myShare/tree/master/02.%E6%9D%82%E9%A1%B9%E6%95%B4%E7%90%86/01.css%E7%AE%80%E5%8D%95%E8%A7%86%E5%B7%AE%E6%95%88%E6%9E%9C'
    },
    { name: '38.vue3v-model修饰符转jsx.md' },
    { name: '37.啥也不是.md' },
    { name: '36.Vue3 组件标注TS类型.md' },
    { name: '35.props更新如何触发子组件重新渲染.md' },
    { name: '34.简易axios封装.md' },
    { name: '33.动态import()打包后的文件名称定义.md' },
    { name: '32.常用指令2.md' },
    { name: '31.工具函数.md' },
    { name: '30.webpack拆包-关于 splitChunks的几个重点属性解析.md' },
    { name: '29.批量导入.md' },
    { name: '28.递归函数.md' },
    { name: '27.删除node_modules.md' },
    { name: '26.vue3一个全局提示弹窗.md' },
    { name: '25.js判断参数类型.md' },
    { name: '24.Vue和React对比学习之Hooks.md' },
    { name: '23.数组排序.md' },
    { name: '22.常用git操作.md' },
    { name: '21.npm-run-xxx执行了什么.md' },
    { name: '20.vue3配置externals引入外部CDN.md' },
    { name: '19.vue的class过渡.md' },
    { name: '18.js自定义事件定义与触发.md' },
    { name: '17.indexDB和离线web.md' },
    { name: '16.IntersectionObserve观察元素.md' },
    { name: '15.关于301永久重定向.md' },
    { name: '14.Proxy与Reflect的配合.md' },
    { name: '13.Watch与WatchEffect应用之区别.md' },
    { name: '12.uniapp中rpx与px互相转化.md' },
    { name: '11.vue3响应式原理杂谈.md' },
    { name: '10.Vue2响应式原理与修改了数组数值视图不更新.md' },
    { name: '09.观察者模式与发布订阅模式.md' },
    { name: '08.JavaScript垃圾回收机制.md' },
    { name: '07.vue和react.md' },
    { name: '06.JSON不做深拷贝原因.md' },
    { name: '05.Dom可能的性能问题.md' },
    { name: '04.async可能的死锁.md' },
    { name: '03.vue.use做了什么.md' },
    { name: '02.常用css.md' },
    { name: '01.惰性求值.md' }
  ]
}
