export default {
  name: '16.日常分享-基础',
  children: [
    { name: '01.关于位置与尺寸的API.md' },
    { name: '02.元素的绝对位置与相对位置.md' },
    { name: '03.mac停靠栏.md' },
    { name: '04.鼠标滚轮事件.md' },
    { name: '05.滚轮实例.md' },
    { name: '06.气泡效果.md' },
    { name: '07.气泡效果加强.md' },
    { name: '08.小demo.md' },
    { name: '09.自定义右键菜单.md' },
    {
      name: 'img',
      children: [
        { name: '1about.jpg' },
        { name: '2about.jpg' },
        { name: '3about.jpg' },
        { name: '4about.jpg' },
        { name: 'about1.jpg' },
        { name: 'about3.jpg' },
        { name: 'bg1.jpg' },
        { name: 'bg2.jpg' },
        { name: 'bg3.jpg' },
        { name: 'bg4.jpg' },
        { name: 'bg5.jpg' },
        { name: 'binoli.png' },
        { name: 'greenLine.png' },
        { name: 'home.png' },
        { name: 'home_gruen.png' },
        { name: 'logo.png' },
        { name: 'menuIndicator.png' },
        { name: 'musicoff.gif' },
        { name: 'musicon.gif' },
        { name: 'pencel1.png' },
        { name: 'pencel2.png' },
        { name: 'pencel3.png' },
        { name: 'pic1.png' },
        { name: 'pic2.png' },
        { name: 'pic3.png' },
        { name: 'pic4.png' },
        { name: 'pic5.png' },
        { name: 'plane1.png' },
        { name: 'plane2.png' },
        { name: 'plane3.png' },
        { name: 'plus_row.png' },
        { name: 'robot.png' },
        { name: 's1.jpg' },
        { name: 's2.jpg' },
        { name: 's3.jpg' },
        { name: 's4.png' },
        { name: 's5.jpg' },
        { name: 's6.jpg' },
        { name: 'team.png' },
        { name: 'tip_arrow_bottom.png' },
        { name: 'tip_arrow_top.png' },
        { name: 'tip_bottom.png' },
        { name: 'tip_left.png' },
        { name: 'tip_left_bottom.png' },
        { name: 'tip_left_top.png' },
        { name: 'tip_right.png' },
        { name: 'tip_right_bottom.png' },
        { name: 'tip_right_top.png' },
        { name: 'tip_top.png' },
        { name: 'worksimg1 (1).jpg' },
        { name: 'worksimg1.jpg' },
        { name: 'worksimg2.jpg' },
        { name: 'worksimg3.jpg' },
        { name: 'worksimg4.jpg' },
        { name: 'zoomico.png' },
        { name: '参考1.png' },
        { name: '参考2.png' }
      ]
    }
  ]
}
