import { drawUnit, drawAvatar } from '../draw-utils.js'

export const config = {
  IDLE_SPEED: 0.008,
  WALK_SPEED: 0.1,
}

const DRAGON_COLORS = {
  body: '#9B8ACB',
  bodyLight: '#B8A8DB',
  bodyDark: '#7A6AAB',
  bodyPink: '#E8C8D8',
  fin: '#D8C8F0',
  finLight: '#E8E0F8',
  finDark: '#A898C0',
  eye: '#5A4A8A',
  eyeLight: '#8A7AC0',
  eyeWhite: '#FFFFFF',
  pupil: '#2A1A4A',
  pupilGlow: '#8060C0',
  blush: '#F0A0B0',
  blushLight: '#FFD0D8',
  horn: '#E8D8C0',
  hornDark: '#C8B8A0',
  hornTip: '#F8E8D0',
  wing: '#C8B8E0',
  wingLight: '#E0D8F0',
  wingDark: '#A898C8',
  tailTip: '#F0A0B0',
  highlight: '#FFFFFF',
  sparkle: '#FFE0F0',
};

const DRAGON_FACE_DOWN = [
  [8, 0, DRAGON_COLORS.hornDark], [9, 0, DRAGON_COLORS.hornDark], [10, 0, DRAGON_COLORS.hornDark], [11, 0, DRAGON_COLORS.hornDark],
  [7, 1, DRAGON_COLORS.horn], [8, 1, DRAGON_COLORS.hornTip], [9, 1, DRAGON_COLORS.horn], [10, 1, DRAGON_COLORS.horn], [11, 1, DRAGON_COLORS.hornTip], [12, 1, DRAGON_COLORS.horn],
  [7, 2, DRAGON_COLORS.hornDark], [8, 2, DRAGON_COLORS.horn], [9, 2, DRAGON_COLORS.horn], [10, 2, DRAGON_COLORS.horn], [11, 2, DRAGON_COLORS.horn], [12, 2, DRAGON_COLORS.hornDark],
  [6, 3, DRAGON_COLORS.bodyLight], [7, 3, DRAGON_COLORS.bodyLight], [8, 3, DRAGON_COLORS.body], [9, 3, DRAGON_COLORS.body], [10, 3, DRAGON_COLORS.body], [11, 3, DRAGON_COLORS.body], [12, 3, DRAGON_COLORS.bodyLight], [13, 3, DRAGON_COLORS.bodyLight],
  [5, 4, DRAGON_COLORS.bodyLight], [6, 4, DRAGON_COLORS.body], [7, 4, DRAGON_COLORS.body], [8, 4, DRAGON_COLORS.bodyLight], [9, 4, DRAGON_COLORS.bodyLight], [10, 4, DRAGON_COLORS.bodyLight], [11, 4, DRAGON_COLORS.body], [12, 4, DRAGON_COLORS.body], [13, 4, DRAGON_COLORS.bodyLight], [14, 4, DRAGON_COLORS.bodyLight],
  [5, 5, DRAGON_COLORS.bodyLight], [6, 5, DRAGON_COLORS.body], [7, 5, DRAGON_COLORS.bodyLight], [8, 5, DRAGON_COLORS.body], [9, 5, DRAGON_COLORS.body], [10, 5, DRAGON_COLORS.body], [11, 5, DRAGON_COLORS.bodyLight], [12, 5, DRAGON_COLORS.body], [13, 5, DRAGON_COLORS.bodyLight], [14, 5, DRAGON_COLORS.bodyLight],
  [4, 4, DRAGON_COLORS.fin], [4, 5, DRAGON_COLORS.finLight],
  [15, 4, DRAGON_COLORS.fin], [15, 5, DRAGON_COLORS.finLight],
  [6, 6, DRAGON_COLORS.bodyLight], [7, 6, DRAGON_COLORS.eyeWhite], [8, 6, DRAGON_COLORS.eyeWhite], [9, 6, DRAGON_COLORS.bodyDark], [10, 6, DRAGON_COLORS.bodyDark], [11, 6, DRAGON_COLORS.eyeWhite], [12, 6, DRAGON_COLORS.eyeWhite], [13, 6, DRAGON_COLORS.bodyLight],
  [6, 7, DRAGON_COLORS.eyeWhite], [7, 7, DRAGON_COLORS.eye], [8, 7, DRAGON_COLORS.eye], [9, 7, DRAGON_COLORS.pupil], [10, 7, DRAGON_COLORS.pupil], [11, 7, DRAGON_COLORS.eye], [12, 7, DRAGON_COLORS.eye], [13, 7, DRAGON_COLORS.eyeWhite],
  [7, 6, DRAGON_COLORS.highlight], [8, 6, DRAGON_COLORS.highlight], [11, 6, DRAGON_COLORS.highlight], [12, 6, DRAGON_COLORS.highlight],
  [7, 7, DRAGON_COLORS.sparkle], [12, 7, DRAGON_COLORS.sparkle],
  [5, 7, DRAGON_COLORS.blush], [6, 7, DRAGON_COLORS.blushLight],
  [13, 7, DRAGON_COLORS.blushLight], [14, 7, DRAGON_COLORS.blush],
  [7, 8, DRAGON_COLORS.bodyDark], [8, 8, DRAGON_COLORS.bodyLight], [9, 8, DRAGON_COLORS.bodyLight], [10, 8, DRAGON_COLORS.bodyLight], [11, 8, DRAGON_COLORS.bodyLight], [12, 8, DRAGON_COLORS.bodyDark],
  [8, 9, DRAGON_COLORS.bodyPink], [9, 9, DRAGON_COLORS.bodyPink], [10, 9, DRAGON_COLORS.bodyPink], [11, 9, DRAGON_COLORS.bodyPink],
  [5, 10, DRAGON_COLORS.bodyDark], [6, 10, DRAGON_COLORS.body], [7, 10, DRAGON_COLORS.bodyLight], [8, 10, DRAGON_COLORS.bodyPink], [9, 10, DRAGON_COLORS.bodyPink], [10, 10, DRAGON_COLORS.bodyPink], [11, 10, DRAGON_COLORS.bodyPink], [12, 10, DRAGON_COLORS.bodyLight], [13, 10, DRAGON_COLORS.body], [14, 10, DRAGON_COLORS.bodyDark],
  [4, 11, DRAGON_COLORS.bodyDark], [5, 11, DRAGON_COLORS.body], [6, 11, DRAGON_COLORS.bodyLight], [7, 11, DRAGON_COLORS.bodyPink], [8, 11, DRAGON_COLORS.bodyPink], [9, 11, DRAGON_COLORS.bodyPink], [10, 11, DRAGON_COLORS.bodyPink], [11, 11, DRAGON_COLORS.bodyPink], [12, 11, DRAGON_COLORS.bodyLight], [13, 11, DRAGON_COLORS.body], [14, 11, DRAGON_COLORS.bodyDark],
  [4, 12, DRAGON_COLORS.bodyDark], [5, 12, DRAGON_COLORS.body], [6, 12, DRAGON_COLORS.bodyLight], [7, 12, DRAGON_COLORS.bodyLight], [8, 12, DRAGON_COLORS.body], [9, 12, DRAGON_COLORS.body], [10, 12, DRAGON_COLORS.body], [11, 12, DRAGON_COLORS.bodyLight], [12, 12, DRAGON_COLORS.bodyLight], [13, 12, DRAGON_COLORS.body], [14, 12, DRAGON_COLORS.bodyDark],
  [5, 13, DRAGON_COLORS.bodyDark], [6, 13, DRAGON_COLORS.bodyLight], [7, 13, DRAGON_COLORS.horn], [8, 13, DRAGON_COLORS.horn], [9, 13, DRAGON_COLORS.horn], [10, 13, DRAGON_COLORS.horn], [11, 13, DRAGON_COLORS.horn], [12, 13, DRAGON_COLORS.horn], [13, 13, DRAGON_COLORS.bodyLight], [14, 13, DRAGON_COLORS.bodyDark],
  [4, 14, DRAGON_COLORS.bodyDark], [5, 14, DRAGON_COLORS.bodyLight], [6, 14, DRAGON_COLORS.bodyLight], [7, 14, DRAGON_COLORS.hornDark], [8, 14, DRAGON_COLORS.hornDark], [9, 14, DRAGON_COLORS.hornDark], [10, 14, DRAGON_COLORS.hornDark], [11, 14, DRAGON_COLORS.hornDark], [12, 14, DRAGON_COLORS.hornDark], [13, 14, DRAGON_COLORS.bodyLight], [14, 14, DRAGON_COLORS.bodyLight], [15, 14, DRAGON_COLORS.bodyDark],
  [2, 12, DRAGON_COLORS.finDark], [3, 12, DRAGON_COLORS.fin],
  [2, 13, DRAGON_COLORS.fin], [3, 13, DRAGON_COLORS.finLight],
  [2, 14, DRAGON_COLORS.finDark], [3, 14, DRAGON_COLORS.tailTip], [4, 14, DRAGON_COLORS.tailTip],
  [2, 15, DRAGON_COLORS.fin], [3, 15, DRAGON_COLORS.tailTip],
];

const DRAGON_FACE_LEFT = [
  [8, 0, DRAGON_COLORS.hornDark], [9, 0, DRAGON_COLORS.hornDark], [10, 0, DRAGON_COLORS.hornTip],
  [7, 1, DRAGON_COLORS.horn], [8, 1, DRAGON_COLORS.horn], [9, 1, DRAGON_COLORS.hornTip], [10, 1, DRAGON_COLORS.horn], [11, 1, DRAGON_COLORS.hornDark],
  [5, 2, DRAGON_COLORS.bodyLight], [6, 2, DRAGON_COLORS.body], [7, 2, DRAGON_COLORS.bodyLight], [8, 2, DRAGON_COLORS.body], [9, 2, DRAGON_COLORS.bodyLight], [10, 2, DRAGON_COLORS.body], [11, 2, DRAGON_COLORS.bodyDark],
  [4, 3, DRAGON_COLORS.bodyLight], [5, 3, DRAGON_COLORS.body], [6, 3, DRAGON_COLORS.bodyLight], [7, 3, DRAGON_COLORS.body], [8, 3, DRAGON_COLORS.bodyLight], [9, 3, DRAGON_COLORS.body], [10, 3, DRAGON_COLORS.bodyDark], [11, 3, DRAGON_COLORS.bodyDark],
  [4, 4, DRAGON_COLORS.bodyLight], [5, 4, DRAGON_COLORS.body], [6, 4, DRAGON_COLORS.bodyLight], [7, 4, DRAGON_COLORS.body], [8, 4, DRAGON_COLORS.bodyDark], [9, 4, DRAGON_COLORS.bodyDark], [10, 4, DRAGON_COLORS.bodyDark],
  [3, 3, DRAGON_COLORS.fin], [3, 4, DRAGON_COLORS.finLight],
  [5, 5, DRAGON_COLORS.eyeWhite], [6, 5, DRAGON_COLORS.eye], [7, 5, DRAGON_COLORS.eye], [8, 5, DRAGON_COLORS.pupil], [9, 5, DRAGON_COLORS.bodyDark],
  [5, 6, DRAGON_COLORS.eyeWhite], [6, 6, DRAGON_COLORS.eye], [7, 6, DRAGON_COLORS.pupil], [8, 6, DRAGON_COLORS.pupil], [9, 6, DRAGON_COLORS.bodyDark],
  [6, 5, DRAGON_COLORS.highlight], [7, 5, DRAGON_COLORS.highlight],
  [6, 6, DRAGON_COLORS.sparkle],
  [4, 6, DRAGON_COLORS.blush], [4, 7, DRAGON_COLORS.blushLight],
  [6, 7, DRAGON_COLORS.bodyDark], [7, 7, DRAGON_COLORS.bodyLight], [8, 7, DRAGON_COLORS.bodyLight], [9, 7, DRAGON_COLORS.bodyDark],
  [7, 8, DRAGON_COLORS.bodyPink], [8, 8, DRAGON_COLORS.bodyPink],
  [4, 9, DRAGON_COLORS.bodyDark], [5, 9, DRAGON_COLORS.body], [6, 9, DRAGON_COLORS.bodyLight], [7, 9, DRAGON_COLORS.bodyPink], [8, 9, DRAGON_COLORS.bodyPink], [9, 9, DRAGON_COLORS.bodyPink], [10, 9, DRAGON_COLORS.bodyDark],
  [3, 10, DRAGON_COLORS.bodyDark], [4, 10, DRAGON_COLORS.body], [5, 10, DRAGON_COLORS.bodyLight], [6, 10, DRAGON_COLORS.bodyLight], [7, 10, DRAGON_COLORS.bodyPink], [8, 10, DRAGON_COLORS.bodyPink], [9, 10, DRAGON_COLORS.bodyDark], [10, 10, DRAGON_COLORS.bodyDark], [11, 10, DRAGON_COLORS.bodyDark],
  [3, 11, DRAGON_COLORS.bodyDark], [4, 11, DRAGON_COLORS.body], [5, 11, DRAGON_COLORS.bodyLight], [6, 11, DRAGON_COLORS.bodyLight], [7, 11, DRAGON_COLORS.body], [8, 11, DRAGON_COLORS.bodyDark], [9, 11, DRAGON_COLORS.bodyDark], [10, 11, DRAGON_COLORS.bodyDark],
  [4, 12, DRAGON_COLORS.bodyDark], [5, 12, DRAGON_COLORS.bodyLight], [6, 12, DRAGON_COLORS.horn], [7, 12, DRAGON_COLORS.horn], [8, 12, DRAGON_COLORS.hornDark], [9, 12, DRAGON_COLORS.bodyDark],
  [3, 13, DRAGON_COLORS.bodyDark], [4, 13, DRAGON_COLORS.bodyLight], [5, 13, DRAGON_COLORS.hornDark], [6, 13, DRAGON_COLORS.hornDark], [7, 13, DRAGON_COLORS.hornDark], [8, 13, DRAGON_COLORS.bodyDark],
  [2, 11, DRAGON_COLORS.finDark], [2, 12, DRAGON_COLORS.fin], [3, 12, DRAGON_COLORS.finLight],
  [2, 13, DRAGON_COLORS.finDark], [2, 14, DRAGON_COLORS.fin], [3, 14, DRAGON_COLORS.tailTip], [4, 14, DRAGON_COLORS.tailTip],
];

const DRAGON_FACE_RIGHT = [
  [9, 0, DRAGON_COLORS.hornTip], [10, 0, DRAGON_COLORS.hornDark], [11, 0, DRAGON_COLORS.hornDark],
  [8, 1, DRAGON_COLORS.horn], [9, 1, DRAGON_COLORS.hornTip], [10, 1, DRAGON_COLORS.horn], [11, 1, DRAGON_COLORS.horn], [12, 1, DRAGON_COLORS.horn],
  [8, 2, DRAGON_COLORS.body], [9, 2, DRAGON_COLORS.bodyLight], [10, 2, DRAGON_COLORS.body], [11, 2, DRAGON_COLORS.bodyLight], [12, 2, DRAGON_COLORS.body], [13, 2, DRAGON_COLORS.bodyLight], [14, 2, DRAGON_COLORS.bodyLight],
  [8, 3, DRAGON_COLORS.bodyDark], [9, 3, DRAGON_COLORS.body], [10, 3, DRAGON_COLORS.bodyLight], [11, 3, DRAGON_COLORS.body], [12, 3, DRAGON_COLORS.bodyLight], [13, 3, DRAGON_COLORS.body], [14, 3, DRAGON_COLORS.bodyLight], [15, 3, DRAGON_COLORS.bodyLight],
  [9, 4, DRAGON_COLORS.bodyDark], [10, 4, DRAGON_COLORS.bodyDark], [11, 4, DRAGON_COLORS.bodyDark], [12, 4, DRAGON_COLORS.bodyLight], [13, 4, DRAGON_COLORS.body], [14, 4, DRAGON_COLORS.bodyLight], [15, 4, DRAGON_COLORS.bodyLight],
  [16, 3, DRAGON_COLORS.finLight], [16, 4, DRAGON_COLORS.fin],
  [10, 5, DRAGON_COLORS.bodyDark], [11, 5, DRAGON_COLORS.pupil], [12, 5, DRAGON_COLORS.eye], [13, 5, DRAGON_COLORS.eye], [14, 5, DRAGON_COLORS.eyeWhite],
  [10, 6, DRAGON_COLORS.bodyDark], [11, 6, DRAGON_COLORS.pupil], [12, 6, DRAGON_COLORS.pupil], [13, 6, DRAGON_COLORS.eye], [14, 6, DRAGON_COLORS.eyeWhite],
  [12, 5, DRAGON_COLORS.highlight], [13, 5, DRAGON_COLORS.highlight],
  [13, 6, DRAGON_COLORS.sparkle],
  [15, 6, DRAGON_COLORS.blushLight], [15, 7, DRAGON_COLORS.blush],
  [10, 7, DRAGON_COLORS.bodyDark], [11, 7, DRAGON_COLORS.bodyLight], [12, 7, DRAGON_COLORS.bodyLight], [13, 7, DRAGON_COLORS.bodyDark],
  [11, 8, DRAGON_COLORS.bodyPink], [12, 8, DRAGON_COLORS.bodyPink],
  [10, 9, DRAGON_COLORS.bodyDark], [11, 9, DRAGON_COLORS.bodyPink], [12, 9, DRAGON_COLORS.bodyPink], [13, 9, DRAGON_COLORS.bodyLight], [14, 9, DRAGON_COLORS.body], [15, 9, DRAGON_COLORS.bodyDark],
  [8, 10, DRAGON_COLORS.bodyDark], [9, 10, DRAGON_COLORS.bodyDark], [10, 10, DRAGON_COLORS.bodyDark], [11, 10, DRAGON_COLORS.bodyPink], [12, 10, DRAGON_COLORS.bodyPink], [13, 10, DRAGON_COLORS.bodyLight], [14, 10, DRAGON_COLORS.bodyLight], [15, 10, DRAGON_COLORS.body], [16, 10, DRAGON_COLORS.bodyDark],
  [10, 11, DRAGON_COLORS.bodyDark], [11, 11, DRAGON_COLORS.bodyDark], [12, 11, DRAGON_COLORS.body], [13, 11, DRAGON_COLORS.bodyLight], [14, 11, DRAGON_COLORS.bodyLight], [15, 11, DRAGON_COLORS.body], [16, 11, DRAGON_COLORS.bodyDark],
  [10, 12, DRAGON_COLORS.bodyDark], [11, 12, DRAGON_COLORS.hornDark], [12, 12, DRAGON_COLORS.horn], [13, 12, DRAGON_COLORS.horn], [14, 12, DRAGON_COLORS.bodyLight], [15, 12, DRAGON_COLORS.bodyDark],
  [10, 13, DRAGON_COLORS.bodyDark], [11, 13, DRAGON_COLORS.hornDark], [12, 13, DRAGON_COLORS.hornDark], [13, 13, DRAGON_COLORS.hornDark], [14, 13, DRAGON_COLORS.bodyLight], [15, 13, DRAGON_COLORS.bodyLight], [16, 13, DRAGON_COLORS.bodyDark],
  [16, 11, DRAGON_COLORS.finDark], [17, 11, DRAGON_COLORS.fin], [17, 12, DRAGON_COLORS.finLight], [17, 12, DRAGON_COLORS.fin],
  [16, 13, DRAGON_COLORS.finDark], [16, 14, DRAGON_COLORS.tailTip], [17, 14, DRAGON_COLORS.fin],
];

const DRAGON_FACE_UP = [
  [8, 0, DRAGON_COLORS.hornDark], [9, 0, DRAGON_COLORS.hornDark], [10, 0, DRAGON_COLORS.hornDark], [11, 0, DRAGON_COLORS.hornDark],
  [7, 1, DRAGON_COLORS.horn], [8, 1, DRAGON_COLORS.horn], [9, 1, DRAGON_COLORS.hornTip], [10, 1, DRAGON_COLORS.horn], [11, 1, DRAGON_COLORS.hornTip], [12, 1, DRAGON_COLORS.horn],
  [7, 2, DRAGON_COLORS.hornDark], [8, 2, DRAGON_COLORS.horn], [9, 2, DRAGON_COLORS.horn], [10, 2, DRAGON_COLORS.horn], [11, 2, DRAGON_COLORS.horn], [12, 2, DRAGON_COLORS.hornDark],
  [6, 3, DRAGON_COLORS.bodyLight], [7, 3, DRAGON_COLORS.body], [8, 3, DRAGON_COLORS.body], [9, 3, DRAGON_COLORS.body], [10, 3, DRAGON_COLORS.body], [11, 3, DRAGON_COLORS.body], [12, 3, DRAGON_COLORS.body], [13, 3, DRAGON_COLORS.bodyLight],
  [5, 4, DRAGON_COLORS.bodyLight], [6, 4, DRAGON_COLORS.body], [7, 4, DRAGON_COLORS.body], [8, 4, DRAGON_COLORS.bodyLight], [9, 4, DRAGON_COLORS.bodyLight], [10, 4, DRAGON_COLORS.bodyLight], [11, 4, DRAGON_COLORS.bodyLight], [12, 4, DRAGON_COLORS.body], [13, 4, DRAGON_COLORS.body], [14, 4, DRAGON_COLORS.bodyLight],
  [5, 5, DRAGON_COLORS.bodyLight], [6, 5, DRAGON_COLORS.body], [7, 5, DRAGON_COLORS.bodyLight], [8, 5, DRAGON_COLORS.body], [9, 5, DRAGON_COLORS.body], [10, 5, DRAGON_COLORS.body], [11, 5, DRAGON_COLORS.bodyLight], [12, 5, DRAGON_COLORS.body], [13, 5, DRAGON_COLORS.bodyLight], [14, 5, DRAGON_COLORS.bodyLight],
  [8, 4, DRAGON_COLORS.fin], [9, 4, DRAGON_COLORS.finLight], [10, 4, DRAGON_COLORS.finLight], [11, 4, DRAGON_COLORS.fin],
  [5, 6, DRAGON_COLORS.bodyDark], [6, 6, DRAGON_COLORS.body], [7, 6, DRAGON_COLORS.bodyLight], [8, 6, DRAGON_COLORS.bodyLight], [9, 6, DRAGON_COLORS.bodyLight], [10, 6, DRAGON_COLORS.bodyLight], [11, 6, DRAGON_COLORS.bodyLight], [12, 6, DRAGON_COLORS.bodyLight], [13, 6, DRAGON_COLORS.body], [14, 6, DRAGON_COLORS.bodyDark],
  [4, 7, DRAGON_COLORS.bodyDark], [5, 7, DRAGON_COLORS.body], [6, 7, DRAGON_COLORS.bodyLight], [7, 7, DRAGON_COLORS.bodyLight], [8, 7, DRAGON_COLORS.bodyLight], [9, 7, DRAGON_COLORS.bodyLight], [10, 7, DRAGON_COLORS.bodyLight], [11, 7, DRAGON_COLORS.bodyLight], [12, 7, DRAGON_COLORS.bodyLight], [13, 7, DRAGON_COLORS.body], [14, 7, DRAGON_COLORS.body], [15, 7, DRAGON_COLORS.bodyDark],
  [4, 8, DRAGON_COLORS.bodyDark], [5, 8, DRAGON_COLORS.body], [6, 8, DRAGON_COLORS.bodyLight], [7, 8, DRAGON_COLORS.bodyLight], [8, 8, DRAGON_COLORS.body], [9, 8, DRAGON_COLORS.body], [10, 8, DRAGON_COLORS.body], [11, 8, DRAGON_COLORS.bodyLight], [12, 8, DRAGON_COLORS.bodyLight], [13, 8, DRAGON_COLORS.body], [14, 8, DRAGON_COLORS.bodyDark],
  [5, 9, DRAGON_COLORS.bodyDark], [6, 9, DRAGON_COLORS.bodyLight], [7, 9, DRAGON_COLORS.horn], [8, 9, DRAGON_COLORS.horn], [9, 9, DRAGON_COLORS.hornDark], [10, 9, DRAGON_COLORS.hornDark], [11, 9, DRAGON_COLORS.horn], [12, 9, DRAGON_COLORS.horn], [13, 9, DRAGON_COLORS.bodyLight], [14, 9, DRAGON_COLORS.bodyDark],
  [4, 10, DRAGON_COLORS.bodyDark], [5, 10, DRAGON_COLORS.bodyLight], [6, 10, DRAGON_COLORS.bodyLight], [7, 10, DRAGON_COLORS.hornDark], [8, 10, DRAGON_COLORS.hornDark], [9, 10, DRAGON_COLORS.hornDark], [10, 10, DRAGON_COLORS.hornDark], [11, 10, DRAGON_COLORS.hornDark], [12, 10, DRAGON_COLORS.hornDark], [13, 10, DRAGON_COLORS.bodyLight], [14, 10, DRAGON_COLORS.bodyLight], [15, 10, DRAGON_COLORS.bodyDark],
  [3, 8, DRAGON_COLORS.finDark], [2, 9, DRAGON_COLORS.fin], [2, 10, DRAGON_COLORS.finLight],
  [3, 9, DRAGON_COLORS.fin], [2, 11, DRAGON_COLORS.finDark], [2, 12, DRAGON_COLORS.fin], [3, 12, DRAGON_COLORS.tailTip],
  [3, 10, DRAGON_COLORS.finLight], [3, 11, DRAGON_COLORS.tailTip],
];

const IDLE_FRAMES = [
  [{ pixels: [] }],
  [{ pixels: [
    [7, 6, DRAGON_COLORS.body], [8, 6, DRAGON_COLORS.bodyLight],
    [7, 7, DRAGON_COLORS.body], [8, 7, DRAGON_COLORS.bodyLight],
    [11, 6, DRAGON_COLORS.bodyLight], [12, 6, DRAGON_COLORS.body],
    [11, 7, DRAGON_COLORS.bodyLight], [12, 7, DRAGON_COLORS.body],
    [7, 6, DRAGON_COLORS.bodyLight], [8, 6, DRAGON_COLORS.bodyLight],
    [11, 6, DRAGON_COLORS.bodyLight], [12, 6, DRAGON_COLORS.bodyLight],
    [6, 11, DRAGON_COLORS.bodyLight], [13, 11, DRAGON_COLORS.bodyLight],
  ]}],
  [{ pixels: [] }],
  [{ pixels: [
    [2, 11, DRAGON_COLORS.finDark], [3, 11, DRAGON_COLORS.fin],
    [2, 12, DRAGON_COLORS.fin], [3, 12, DRAGON_COLORS.finLight],
    [2, 13, DRAGON_COLORS.finDark], [3, 13, DRAGON_COLORS.tailTip], [4, 13, DRAGON_COLORS.tailTip],
    [2, 14, DRAGON_COLORS.fin], [3, 14, DRAGON_COLORS.tailTip],
    [4, 15, DRAGON_COLORS.finDark],
    [5, 1, DRAGON_COLORS.sparkle],
    [14, 2, DRAGON_COLORS.sparkle],
    [3, 8, DRAGON_COLORS.highlight],
    [16, 9, DRAGON_COLORS.highlight],
  ]}],
];

const WALK_FRAMES = [
  [{ pixels: [
    [5, 14, DRAGON_COLORS.bodyLight], [6, 14, DRAGON_COLORS.bodyLight],
    [7, 13, DRAGON_COLORS.horn], [8, 13, DRAGON_COLORS.horn], [9, 13, DRAGON_COLORS.horn], [10, 13, DRAGON_COLORS.horn], [11, 13, DRAGON_COLORS.horn], [12, 13, DRAGON_COLORS.horn],
    [5, 14, DRAGON_COLORS.bodyDark], [6, 14, DRAGON_COLORS.bodyLight], [7, 14, DRAGON_COLORS.hornDark], [8, 14, DRAGON_COLORS.hornDark], [9, 14, DRAGON_COLORS.hornDark], [10, 14, DRAGON_COLORS.hornDark], [11, 14, DRAGON_COLORS.hornDark], [12, 14, DRAGON_COLORS.hornDark], [13, 14, DRAGON_COLORS.bodyLight], [14, 14, DRAGON_COLORS.bodyLight],
  ]}],
  [{ pixels: [
    [5, 13, DRAGON_COLORS.bodyDark], [6, 13, DRAGON_COLORS.bodyLight], [7, 13, DRAGON_COLORS.horn], [8, 13, DRAGON_COLORS.horn], [9, 13, DRAGON_COLORS.horn], [10, 13, DRAGON_COLORS.horn], [11, 13, DRAGON_COLORS.horn], [12, 13, DRAGON_COLORS.horn], [13, 13, DRAGON_COLORS.bodyLight], [14, 13, DRAGON_COLORS.bodyDark],
    [4, 14, DRAGON_COLORS.bodyDark], [5, 14, DRAGON_COLORS.bodyLight], [6, 14, DRAGON_COLORS.bodyLight], [7, 14, DRAGON_COLORS.hornDark], [8, 14, DRAGON_COLORS.hornDark], [9, 14, DRAGON_COLORS.hornDark], [10, 14, DRAGON_COLORS.hornDark], [11, 14, DRAGON_COLORS.hornDark], [12, 14, DRAGON_COLORS.hornDark], [13, 14, DRAGON_COLORS.bodyLight], [14, 14, DRAGON_COLORS.bodyLight], [15, 14, DRAGON_COLORS.bodyDark],
  ]}],
];

export const drawPet = (ctx, currentUnit) => drawUnit(ctx, currentUnit, {
  down: DRAGON_FACE_DOWN,
  up: DRAGON_FACE_UP,
  left: DRAGON_FACE_LEFT,
  right: DRAGON_FACE_RIGHT,
  walk: WALK_FRAMES,
  idle: IDLE_FRAMES,
})

const PET_AVATAR = [
  [6, 0, DRAGON_COLORS.horn], [7, 0, DRAGON_COLORS.hornTip], [8, 0, DRAGON_COLORS.hornTip], [9, 0, DRAGON_COLORS.hornTip], [10, 0, DRAGON_COLORS.hornTip], [11, 0, DRAGON_COLORS.horn],
  [5, 1, DRAGON_COLORS.hornDark], [6, 1, DRAGON_COLORS.horn], [7, 1, DRAGON_COLORS.horn], [8, 1, DRAGON_COLORS.horn], [9, 1, DRAGON_COLORS.horn], [10, 1, DRAGON_COLORS.horn], [11, 1, DRAGON_COLORS.hornDark],
  [4, 2, DRAGON_COLORS.bodyLight], [5, 2, DRAGON_COLORS.bodyLight], [6, 2, DRAGON_COLORS.body], [7, 2, DRAGON_COLORS.body], [8, 2, DRAGON_COLORS.body], [9, 2, DRAGON_COLORS.body], [10, 2, DRAGON_COLORS.body], [11, 2, DRAGON_COLORS.bodyLight], [12, 2, DRAGON_COLORS.bodyLight],
  [3, 3, DRAGON_COLORS.bodyLight], [4, 3, DRAGON_COLORS.body], [5, 3, DRAGON_COLORS.bodyLight], [6, 3, DRAGON_COLORS.bodyLight], [7, 3, DRAGON_COLORS.bodyLight], [8, 3, DRAGON_COLORS.bodyLight], [9, 3, DRAGON_COLORS.bodyLight], [10, 3, DRAGON_COLORS.bodyLight], [11, 3, DRAGON_COLORS.bodyLight], [12, 3, DRAGON_COLORS.bodyLight], [13, 3, DRAGON_COLORS.bodyLight],
  [2, 2, DRAGON_COLORS.finLight], [2, 3, DRAGON_COLORS.fin],
  [13, 2, DRAGON_COLORS.fin], [13, 3, DRAGON_COLORS.finLight],
  [4, 4, DRAGON_COLORS.eyeWhite], [5, 4, DRAGON_COLORS.eyeWhite], [6, 4, DRAGON_COLORS.eyeWhite], [7, 4, DRAGON_COLORS.eyeWhite], [8, 4, DRAGON_COLORS.eyeWhite], [9, 4, DRAGON_COLORS.eyeWhite], [10, 4, DRAGON_COLORS.eyeWhite], [11, 4, DRAGON_COLORS.eyeWhite], [12, 4, DRAGON_COLORS.eyeWhite],
  [4, 5, DRAGON_COLORS.eyeWhite], [5, 5, DRAGON_COLORS.eye], [6, 5, DRAGON_COLORS.eye], [7, 5, DRAGON_COLORS.eye], [8, 5, DRAGON_COLORS.eye], [9, 5, DRAGON_COLORS.eye], [10, 5, DRAGON_COLORS.eye], [11, 5, DRAGON_COLORS.eye], [12, 5, DRAGON_COLORS.eyeWhite],
  [5, 5, DRAGON_COLORS.pupil], [6, 5, DRAGON_COLORS.pupil], [7, 5, DRAGON_COLORS.pupil], [8, 5, DRAGON_COLORS.pupil], [9, 5, DRAGON_COLORS.pupil], [10, 5, DRAGON_COLORS.pupil],
  [5, 4, DRAGON_COLORS.highlight], [6, 4, DRAGON_COLORS.highlight], [7, 4, DRAGON_COLORS.highlight], [9, 4, DRAGON_COLORS.highlight], [10, 4, DRAGON_COLORS.highlight], [11, 4, DRAGON_COLORS.highlight],
  [5, 5, DRAGON_COLORS.sparkle], [6, 5, DRAGON_COLORS.sparkle], [9, 5, DRAGON_COLORS.sparkle], [10, 5, DRAGON_COLORS.sparkle],
  [3, 5, DRAGON_COLORS.blush], [3, 6, DRAGON_COLORS.blushLight],
  [12, 5, DRAGON_COLORS.blushLight], [12, 6, DRAGON_COLORS.blush],
  [4, 6, DRAGON_COLORS.eyeWhite], [5, 6, DRAGON_COLORS.eyeWhite], [6, 6, DRAGON_COLORS.eyeWhite], [7, 6, DRAGON_COLORS.eyeWhite], [8, 6, DRAGON_COLORS.eyeWhite], [9, 6, DRAGON_COLORS.eyeWhite], [10, 6, DRAGON_COLORS.eyeWhite], [11, 6, DRAGON_COLORS.eyeWhite], [12, 6, DRAGON_COLORS.eyeWhite],
  [5, 7, DRAGON_COLORS.bodyLight], [6, 7, DRAGON_COLORS.bodyLight], [7, 7, DRAGON_COLORS.bodyLight], [8, 7, DRAGON_COLORS.bodyLight], [9, 7, DRAGON_COLORS.bodyLight], [10, 7, DRAGON_COLORS.bodyLight], [11, 7, DRAGON_COLORS.bodyLight],
  [6, 8, DRAGON_COLORS.bodyDark], [7, 8, DRAGON_COLORS.bodyDark], [8, 8, DRAGON_COLORS.bodyDark], [9, 8, DRAGON_COLORS.bodyDark], [10, 8, DRAGON_COLORS.bodyDark],
  [7, 9, DRAGON_COLORS.bodyPink], [8, 9, DRAGON_COLORS.bodyPink], [9, 9, DRAGON_COLORS.bodyPink],
  [5, 10, DRAGON_COLORS.bodyDark], [6, 10, DRAGON_COLORS.bodyLight], [7, 10, DRAGON_COLORS.bodyPink], [8, 10, DRAGON_COLORS.bodyPink], [9, 10, DRAGON_COLORS.bodyPink], [10, 10, DRAGON_COLORS.bodyLight], [11, 10, DRAGON_COLORS.bodyDark],
  [4, 11, DRAGON_COLORS.bodyDark], [5, 11, DRAGON_COLORS.bodyLight], [6, 11, DRAGON_COLORS.bodyLight], [7, 11, DRAGON_COLORS.bodyLight], [8, 11, DRAGON_COLORS.bodyLight], [9, 11, DRAGON_COLORS.bodyLight], [10, 11, DRAGON_COLORS.bodyLight], [11, 11, DRAGON_COLORS.bodyLight], [12, 11, DRAGON_COLORS.bodyDark],
  [5, 12, DRAGON_COLORS.bodyLight], [6, 12, DRAGON_COLORS.horn], [7, 12, DRAGON_COLORS.horn], [8, 12, DRAGON_COLORS.horn], [9, 12, DRAGON_COLORS.horn], [10, 12, DRAGON_COLORS.horn], [11, 12, DRAGON_COLORS.bodyLight],
  [4, 13, DRAGON_COLORS.bodyLight], [5, 13, DRAGON_COLORS.hornDark], [6, 13, DRAGON_COLORS.hornDark], [7, 13, DRAGON_COLORS.hornDark], [8, 13, DRAGON_COLORS.hornDark], [9, 13, DRAGON_COLORS.hornDark], [10, 13, DRAGON_COLORS.hornDark], [11, 13, DRAGON_COLORS.bodyLight], [12, 13, DRAGON_COLORS.bodyLight],
  [2, 11, DRAGON_COLORS.finDark], [2, 12, DRAGON_COLORS.fin], [2, 13, DRAGON_COLORS.finLight],
  [1, 12, DRAGON_COLORS.fin], [1, 13, DRAGON_COLORS.finDark], [1, 14, DRAGON_COLORS.tailTip],
  [1, 15, DRAGON_COLORS.finLight],
];

export const drawPetAvatar = (ctx, currentUnit, avatarPos) => drawAvatar(ctx, currentUnit, avatarPos, PET_AVATAR)