import { drawUnit, drawAvatar } from '../draw-utils.js'

export const config = {
  IDLE_SPEED: 0.008,
  WALK_SPEED: 0.12,
}

const COLORS = {
  helmet: { 
    gold: '#FFD700', 
    darkGold: '#DAA520', 
    bronze: '#B8860B',
    highlight: '#FFEC8B',
    shadow: '#B8860B'
  },
  hair: {
    brown: '#8B4513',
    dark: '#654321',
    light: '#A0522D',
    highlight: '#CD853F'
  },
  skin: { 
    normal: '#FFDAB9', 
    light: '#F5DEB3', 
    shadow: '#DEB887',
    highlight: '#FFE4C4'
  },
  face: { 
    normal: '#FFDAB9', 
    eye: '#2F2F2F',
    eyeLight: '#4A4A4A',
    brow: '#654321',
    mouth: '#CD5C5C',
    blush: '#FFB6C1'
  },
  armor: { 
    blue: '#4169E1', 
    light: '#6495ED',
    dark: '#1E3A8A',
    highlight: '#87CEEB',
    detail: '#2E4A9A'
  },
  belt: { 
    gold: '#DAA520', 
    yellow: '#FFD700',
    dark: '#B8860B'
  },
  leg: { 
    brown: '#8B4513', 
    dark: '#654321',
    light: '#A0522D',
    boot: '#3D2314'
  },
  shield: { 
    blue: '#4169E1', 
    gold: '#FFD700',
    dark: '#1E3A8A',
    highlight: '#6495ED'
  },
  sword: { 
    silver: '#E8E8E8', 
    gold: '#FFD700',
    dark: '#A9A9A9',
    highlight: '#FFFFFF'
  },
  feather: { 
    red: '#FF4500', 
    orange: '#FF6347',
    yellow: '#FFD700',
    dark: '#DC143C',
    highlight: '#FF6B6B'
  },
  highlight: '#FFFFFF'
};

const PLAYER_AVATAR = [
  [5, 0, COLORS.helmet.darkGold], [6, 0, COLORS.helmet.darkGold], [7, 0, COLORS.helmet.darkGold], [8, 0, COLORS.helmet.darkGold],
  [4, 0, COLORS.helmet.gold], [9, 0, COLORS.helmet.gold],
  [3, 0, COLORS.helmet.highlight], [10, 0, COLORS.helmet.highlight],
  [2, 1, COLORS.feather.red], [3, 1, COLORS.helmet.gold], [4, 1, COLORS.helmet.gold],
  [5, 1, COLORS.helmet.gold], [6, 1, COLORS.helmet.gold], [7, 1, COLORS.helmet.gold], [8, 1, COLORS.helmet.gold],
  [9, 1, COLORS.helmet.gold], [10, 1, COLORS.helmet.gold], [11, 1, COLORS.helmet.gold], [12, 1, COLORS.feather.red],
  [1, 1, COLORS.feather.orange], [13, 1, COLORS.feather.orange],
  [0, 1, COLORS.feather.yellow], [14, 1, COLORS.feather.yellow],
  [2, 2, COLORS.feather.dark], [3, 2, COLORS.helmet.darkGold], [4, 2, COLORS.helmet.darkGold],
  [5, 2, COLORS.helmet.bronze], [6, 2, COLORS.helmet.bronze], [7, 2, COLORS.helmet.bronze], [8, 2, COLORS.helmet.bronze],
  [9, 2, COLORS.helmet.bronze], [10, 2, COLORS.helmet.darkGold], [11, 2, COLORS.helmet.darkGold], [12, 2, COLORS.feather.dark],
  [1, 2, COLORS.feather.red], [13, 2, COLORS.feather.red],
  [2, 3, COLORS.helmet.gold], [3, 3, COLORS.helmet.gold], [4, 3, COLORS.hair.brown],
  [5, 3, COLORS.hair.brown], [6, 3, COLORS.hair.dark], [7, 3, COLORS.hair.dark], [8, 3, COLORS.hair.dark],
  [9, 3, COLORS.hair.brown], [10, 3, COLORS.hair.brown], [11, 3, COLORS.helmet.gold], [12, 3, COLORS.helmet.gold],
  [1, 3, COLORS.feather.orange], [13, 3, COLORS.feather.orange],
  [2, 4, COLORS.hair.light], [3, 4, COLORS.hair.brown], [4, 4, COLORS.hair.brown],
  [5, 4, COLORS.skin.light], [6, 4, COLORS.skin.normal], [7, 4, COLORS.skin.normal], [8, 4, COLORS.skin.normal],
  [9, 4, COLORS.skin.light], [10, 4, COLORS.hair.brown], [11, 4, COLORS.hair.brown], [12, 4, COLORS.hair.light],
  [1, 4, COLORS.feather.highlight], [13, 4, COLORS.feather.highlight],
  [3, 5, COLORS.skin.normal], [4, 5, COLORS.face.eye], [5, 5, COLORS.skin.light],
  [6, 5, COLORS.skin.normal], [7, 5, COLORS.skin.normal], [8, 5, COLORS.skin.normal],
  [9, 5, COLORS.skin.light], [10, 5, COLORS.face.eye], [11, 5, COLORS.skin.normal],
  [3, 5, COLORS.face.brow], [4, 5, COLORS.face.brow], [10, 5, COLORS.face.brow], [11, 5, COLORS.face.brow],
  [4, 4, COLORS.highlight], [5, 4, COLORS.highlight], [9, 4, COLORS.highlight], [10, 4, COLORS.highlight],
  [4, 5, COLORS.highlight], [10, 5, COLORS.highlight],
  [4, 6, COLORS.skin.normal], [5, 6, COLORS.face.mouth], [6, 6, COLORS.face.mouth],
  [7, 6, COLORS.skin.normal], [8, 6, COLORS.skin.normal], [9, 6, COLORS.face.mouth], [10, 6, COLORS.face.mouth],
  [4, 6, COLORS.face.blush], [11, 6, COLORS.face.blush],
  [4, 7, COLORS.skin.shadow], [5, 7, COLORS.skin.normal], [6, 7, COLORS.skin.normal],
  [7, 7, COLORS.skin.normal], [8, 7, COLORS.skin.normal], [9, 7, COLORS.skin.normal], [10, 7, COLORS.skin.shadow],
  [5, 8, COLORS.armor.blue], [6, 8, COLORS.armor.blue], [7, 8, COLORS.armor.blue], [8, 8, COLORS.armor.blue], [9, 8, COLORS.armor.blue],
  [4, 8, COLORS.skin.shadow], [10, 8, COLORS.skin.shadow],
  [4, 9, COLORS.armor.dark], [5, 9, COLORS.armor.blue], [6, 9, COLORS.armor.light],
  [7, 9, COLORS.armor.light], [8, 9, COLORS.armor.light], [9, 9, COLORS.armor.blue], [10, 9, COLORS.armor.dark],
  [3, 9, COLORS.armor.dark], [11, 9, COLORS.armor.dark],
  [3, 10, COLORS.armor.blue], [4, 10, COLORS.armor.blue], [5, 10, COLORS.armor.blue],
  [6, 10, COLORS.belt.gold], [7, 10, COLORS.belt.yellow], [8, 10, COLORS.belt.yellow],
  [9, 10, COLORS.armor.blue], [10, 10, COLORS.armor.blue], [11, 10, COLORS.armor.blue],
  [3, 11, COLORS.armor.blue], [4, 11, COLORS.armor.detail], [5, 11, COLORS.armor.blue],
  [6, 11, COLORS.armor.blue], [7, 11, COLORS.armor.blue], [8, 11, COLORS.armor.blue],
  [9, 11, COLORS.armor.detail], [10, 11, COLORS.armor.blue], [11, 11, COLORS.armor.blue],
]

const FACE_DOWN = [
  [7, 0, COLORS.helmet.darkGold], [8, 0, COLORS.helmet.darkGold], [9, 0, COLORS.helmet.darkGold], [10, 0, COLORS.helmet.darkGold],
  [6, 0, COLORS.helmet.gold], [11, 0, COLORS.helmet.gold],
  [5, 0, COLORS.helmet.highlight], [12, 0, COLORS.helmet.highlight],
  [4, 1, COLORS.feather.red], [5, 1, COLORS.helmet.gold], [6, 1, COLORS.helmet.gold],
  [7, 1, COLORS.helmet.gold], [8, 1, COLORS.helmet.gold], [9, 1, COLORS.helmet.gold], [10, 1, COLORS.helmet.gold],
  [11, 1, COLORS.helmet.gold], [12, 1, COLORS.helmet.gold], [13, 1, COLORS.helmet.gold], [14, 1, COLORS.feather.red],
  [3, 1, COLORS.feather.orange], [15, 1, COLORS.feather.orange],
  [2, 1, COLORS.feather.yellow], [16, 1, COLORS.feather.yellow],
  [4, 2, COLORS.feather.dark], [5, 2, COLORS.helmet.darkGold], [6, 2, COLORS.helmet.darkGold],
  [7, 2, COLORS.helmet.bronze], [8, 2, COLORS.helmet.bronze], [9, 2, COLORS.helmet.bronze], [10, 2, COLORS.helmet.bronze],
  [11, 2, COLORS.helmet.bronze], [12, 2, COLORS.helmet.darkGold], [13, 2, COLORS.helmet.darkGold], [14, 2, COLORS.feather.dark],
  [3, 2, COLORS.feather.red], [15, 2, COLORS.feather.red],
  [4, 3, COLORS.helmet.gold], [5, 3, COLORS.helmet.gold], [6, 3, COLORS.hair.brown],
  [7, 3, COLORS.hair.brown], [8, 3, COLORS.hair.dark], [9, 3, COLORS.hair.dark], [10, 3, COLORS.hair.dark],
  [11, 3, COLORS.hair.brown], [12, 3, COLORS.hair.brown], [13, 3, COLORS.helmet.gold], [14, 3, COLORS.helmet.gold],
  [3, 3, COLORS.feather.orange], [15, 3, COLORS.feather.orange],
  [4, 4, COLORS.hair.light], [5, 4, COLORS.hair.brown], [6, 4, COLORS.hair.brown],
  [7, 4, COLORS.skin.light], [8, 4, COLORS.skin.normal], [9, 4, COLORS.skin.normal], [10, 4, COLORS.skin.normal],
  [11, 4, COLORS.skin.light], [12, 4, COLORS.hair.brown], [13, 4, COLORS.hair.brown], [14, 4, COLORS.hair.light],
  [3, 4, COLORS.feather.highlight], [15, 4, COLORS.feather.highlight],
  [5, 5, COLORS.skin.normal], [6, 5, COLORS.face.eye], [7, 5, COLORS.skin.light],
  [8, 5, COLORS.skin.normal], [9, 5, COLORS.skin.normal], [10, 5, COLORS.skin.normal],
  [11, 5, COLORS.skin.light], [12, 5, COLORS.face.eye], [13, 5, COLORS.skin.normal],
  [5, 5, COLORS.face.brow], [6, 5, COLORS.face.brow], [12, 5, COLORS.face.brow], [13, 5, COLORS.face.brow],
  [6, 6, COLORS.skin.normal], [7, 6, COLORS.face.mouth], [8, 6, COLORS.face.mouth],
  [9, 6, COLORS.skin.normal], [10, 6, COLORS.skin.normal], [11, 6, COLORS.face.mouth], [12, 6, COLORS.face.mouth],
  [6, 6, COLORS.face.blush], [13, 6, COLORS.face.blush],
  [6, 7, COLORS.skin.shadow], [7, 7, COLORS.skin.normal], [8, 7, COLORS.skin.normal],
  [9, 7, COLORS.skin.normal], [10, 7, COLORS.skin.normal], [11, 7, COLORS.skin.normal], [12, 7, COLORS.skin.shadow],
  [7, 8, COLORS.armor.blue], [8, 8, COLORS.armor.blue], [9, 8, COLORS.armor.blue], [10, 8, COLORS.armor.blue], [11, 8, COLORS.armor.blue],
  [6, 8, COLORS.skin.shadow], [12, 8, COLORS.skin.shadow],
  [6, 9, COLORS.armor.dark], [7, 9, COLORS.armor.blue], [8, 9, COLORS.armor.light],
  [9, 9, COLORS.armor.light], [10, 9, COLORS.armor.light], [11, 9, COLORS.armor.blue], [12, 9, COLORS.armor.dark],
  [5, 9, COLORS.armor.dark], [13, 9, COLORS.armor.dark],
  [5, 10, COLORS.armor.blue], [6, 10, COLORS.armor.blue], [7, 10, COLORS.armor.blue],
  [8, 10, COLORS.belt.gold], [9, 10, COLORS.belt.yellow], [10, 10, COLORS.belt.yellow],
  [11, 10, COLORS.armor.blue], [12, 10, COLORS.armor.blue], [13, 10, COLORS.armor.blue],
  [5, 11, COLORS.armor.blue], [6, 11, COLORS.armor.detail], [7, 11, COLORS.armor.blue],
  [8, 11, COLORS.armor.blue], [9, 11, COLORS.armor.blue], [10, 11, COLORS.armor.blue],
  [11, 11, COLORS.armor.detail], [12, 11, COLORS.armor.blue], [13, 11, COLORS.armor.blue],
  [4, 12, COLORS.armor.dark], [5, 12, COLORS.armor.blue], [6, 12, COLORS.armor.blue],
  [7, 12, COLORS.armor.light], [8, 12, COLORS.armor.light], [9, 12, COLORS.armor.light],
  [10, 12, COLORS.armor.light], [11, 12, COLORS.armor.light], [12, 12, COLORS.armor.blue],
  [13, 12, COLORS.armor.blue], [14, 12, COLORS.armor.dark],
  [5, 13, COLORS.belt.dark], [6, 13, COLORS.belt.gold], [7, 13, COLORS.belt.gold],
  [8, 13, COLORS.belt.yellow], [9, 13, COLORS.belt.yellow], [10, 13, COLORS.belt.yellow],
  [11, 13, COLORS.belt.gold], [12, 13, COLORS.belt.gold], [13, 13, COLORS.belt.dark],
  [6, 14, COLORS.leg.dark], [7, 14, COLORS.leg.brown], [8, 14, COLORS.leg.brown],
  [9, 14, COLORS.leg.brown], [10, 14, COLORS.leg.brown], [11, 14, COLORS.leg.brown], [12, 14, COLORS.leg.dark],
  [7, 15, COLORS.leg.boot], [8, 15, COLORS.leg.dark], [9, 15, COLORS.leg.dark], [10, 15, COLORS.leg.dark], [11, 15, COLORS.leg.boot],
  [6, 15, COLORS.leg.dark], [12, 15, COLORS.leg.dark],
];

const FACE_UP = [
  [7, 0, COLORS.helmet.darkGold], [8, 0, COLORS.helmet.darkGold], [9, 0, COLORS.helmet.darkGold], [10, 0, COLORS.helmet.darkGold],
  [6, 0, COLORS.helmet.gold], [11, 0, COLORS.helmet.gold],
  [5, 0, COLORS.helmet.highlight], [12, 0, COLORS.helmet.highlight],
  [4, 1, COLORS.feather.red], [5, 1, COLORS.helmet.gold], [6, 1, COLORS.helmet.gold],
  [7, 1, COLORS.helmet.gold], [8, 1, COLORS.helmet.gold], [9, 1, COLORS.helmet.gold], [10, 1, COLORS.helmet.gold],
  [11, 1, COLORS.helmet.gold], [12, 1, COLORS.helmet.gold], [13, 1, COLORS.helmet.gold], [14, 1, COLORS.feather.red],
  [3, 1, COLORS.feather.orange], [15, 1, COLORS.feather.orange],
  [2, 1, COLORS.feather.yellow], [16, 1, COLORS.feather.yellow],
  [4, 2, COLORS.feather.dark], [5, 2, COLORS.helmet.darkGold], [6, 2, COLORS.helmet.darkGold],
  [7, 2, COLORS.helmet.bronze], [8, 2, COLORS.helmet.bronze], [9, 2, COLORS.helmet.bronze], [10, 2, COLORS.helmet.bronze],
  [11, 2, COLORS.helmet.bronze], [12, 2, COLORS.helmet.darkGold], [13, 2, COLORS.helmet.darkGold], [14, 2, COLORS.feather.dark],
  [3, 2, COLORS.feather.red], [15, 2, COLORS.feather.red],
  [4, 3, COLORS.helmet.gold], [5, 3, COLORS.helmet.gold], [6, 3, COLORS.helmet.darkGold],
  [7, 3, COLORS.helmet.darkGold], [8, 3, COLORS.helmet.darkGold], [9, 3, COLORS.helmet.darkGold],
  [10, 3, COLORS.helmet.darkGold], [11, 3, COLORS.helmet.darkGold], [12, 3, COLORS.helmet.darkGold],
  [13, 3, COLORS.helmet.gold], [14, 3, COLORS.helmet.gold],
  [3, 3, COLORS.feather.orange], [15, 3, COLORS.feather.orange],
  [5, 4, COLORS.hair.dark], [6, 4, COLORS.hair.brown], [7, 4, COLORS.hair.brown],
  [8, 4, COLORS.hair.dark], [9, 4, COLORS.hair.dark], [10, 4, COLORS.hair.dark],
  [11, 4, COLORS.hair.brown], [12, 4, COLORS.hair.brown], [13, 4, COLORS.hair.dark],
  [4, 4, COLORS.feather.highlight], [14, 4, COLORS.feather.highlight],
  [5, 5, COLORS.hair.dark], [6, 5, COLORS.hair.brown], [7, 5, COLORS.hair.brown],
  [8, 5, COLORS.hair.dark], [9, 5, COLORS.hair.dark], [10, 5, COLORS.hair.dark],
  [11, 5, COLORS.hair.brown], [12, 5, COLORS.hair.brown], [13, 5, COLORS.hair.dark],
  [6, 6, COLORS.armor.dark], [7, 6, COLORS.armor.dark], [8, 6, COLORS.armor.dark],
  [9, 6, COLORS.armor.dark], [10, 6, COLORS.armor.dark], [11, 6, COLORS.armor.dark],
  [6, 7, COLORS.armor.dark], [7, 7, COLORS.armor.blue], [8, 7, COLORS.armor.blue],
  [9, 7, COLORS.armor.blue], [10, 7, COLORS.armor.blue], [11, 7, COLORS.armor.blue], [12, 7, COLORS.armor.dark],
  [5, 7, COLORS.armor.dark], [13, 7, COLORS.armor.dark],
  [5, 8, COLORS.armor.dark], [6, 8, COLORS.armor.blue], [7, 8, COLORS.armor.detail],
  [8, 8, COLORS.armor.blue], [9, 8, COLORS.armor.blue], [10, 8, COLORS.armor.blue],
  [11, 8, COLORS.armor.detail], [12, 8, COLORS.armor.blue], [13, 8, COLORS.armor.dark],
  [5, 9, COLORS.armor.blue], [6, 9, COLORS.armor.blue], [7, 9, COLORS.armor.blue],
  [8, 9, COLORS.belt.gold], [9, 9, COLORS.belt.yellow], [10, 9, COLORS.belt.yellow],
  [11, 9, COLORS.armor.blue], [12, 9, COLORS.armor.blue], [13, 9, COLORS.armor.blue],
  [5, 10, COLORS.armor.blue], [6, 10, COLORS.armor.detail], [7, 10, COLORS.armor.blue],
  [8, 10, COLORS.armor.blue], [9, 10, COLORS.armor.blue], [10, 10, COLORS.armor.blue],
  [11, 10, COLORS.armor.detail], [12, 10, COLORS.armor.blue], [13, 10, COLORS.armor.blue],
  [4, 11, COLORS.armor.dark], [5, 11, COLORS.armor.blue], [6, 11, COLORS.armor.blue],
  [7, 11, COLORS.armor.light], [8, 11, COLORS.armor.light], [9, 11, COLORS.armor.light],
  [10, 11, COLORS.armor.light], [11, 11, COLORS.armor.light], [12, 11, COLORS.armor.blue],
  [13, 11, COLORS.armor.blue], [14, 11, COLORS.armor.dark],
  [5, 12, COLORS.belt.dark], [6, 12, COLORS.belt.gold], [7, 12, COLORS.belt.gold],
  [8, 12, COLORS.belt.yellow], [9, 12, COLORS.belt.yellow], [10, 12, COLORS.belt.yellow],
  [11, 12, COLORS.belt.gold], [12, 12, COLORS.belt.gold], [13, 12, COLORS.belt.dark],
  [6, 13, COLORS.leg.dark], [7, 13, COLORS.leg.brown], [8, 13, COLORS.leg.brown],
  [9, 13, COLORS.leg.brown], [10, 13, COLORS.leg.brown], [11, 13, COLORS.leg.brown], [12, 13, COLORS.leg.dark],
  [7, 14, COLORS.leg.boot], [8, 14, COLORS.leg.dark], [9, 14, COLORS.leg.dark], [10, 14, COLORS.leg.dark], [11, 14, COLORS.leg.boot],
  [6, 14, COLORS.leg.dark], [12, 14, COLORS.leg.dark],
  [14, 5, COLORS.sword.dark],
  [14, 6, COLORS.sword.silver],
  [14, 7, COLORS.sword.highlight],
  [14, 8, COLORS.sword.silver],
  [14, 9, COLORS.sword.gold],
  [14, 10, COLORS.sword.gold],
  [14, 11, COLORS.sword.dark],
];

const FACE_LEFT = [
  [7, 0, COLORS.helmet.darkGold], [8, 0, COLORS.helmet.darkGold], [9, 0, COLORS.helmet.darkGold],
  [10, 0, COLORS.helmet.gold], [11, 0, COLORS.helmet.gold],
  [12, 0, COLORS.helmet.highlight],
  [5, 1, COLORS.feather.red], [6, 1, COLORS.helmet.gold], [13, 1, COLORS.helmet.gold],
  [4, 1, COLORS.feather.orange], [14, 1, COLORS.feather.orange],
  [3, 1, COLORS.feather.yellow], [15, 1, COLORS.feather.yellow],
  [2, 1, COLORS.feather.highlight],
  [6, 2, COLORS.helmet.gold], [7, 2, COLORS.helmet.darkGold], [8, 2, COLORS.helmet.darkGold],
  [9, 2, COLORS.helmet.bronze], [10, 2, COLORS.helmet.bronze], [11, 2, COLORS.helmet.darkGold],
  [12, 2, COLORS.helmet.darkGold], [13, 2, COLORS.helmet.gold],
  [5, 2, COLORS.feather.dark], [14, 2, COLORS.feather.dark],
  [6, 3, COLORS.hair.brown], [7, 3, COLORS.hair.brown], [8, 3, COLORS.hair.dark],
  [9, 3, COLORS.hair.dark], [10, 3, COLORS.hair.brown], [11, 3, COLORS.helmet.darkGold],
  [12, 3, COLORS.helmet.darkGold], [13, 3, COLORS.helmet.gold],
  [5, 3, COLORS.feather.highlight], [14, 3, COLORS.feather.highlight],
  [5, 4, COLORS.hair.light], [6, 4, COLORS.skin.light], [7, 4, COLORS.skin.normal],
  [8, 4, COLORS.skin.normal], [9, 4, COLORS.skin.normal], [10, 4, COLORS.skin.normal],
  [11, 4, COLORS.skin.shadow], [12, 4, COLORS.helmet.gold],
  [5, 5, COLORS.skin.normal], [6, 5, COLORS.face.eye], [7, 5, COLORS.skin.normal],
  [8, 5, COLORS.skin.normal], [9, 5, COLORS.skin.normal], [10, 5, COLORS.skin.normal],
  [11, 5, COLORS.skin.shadow],
  [5, 5, COLORS.face.brow], [6, 5, COLORS.face.brow],
  [5, 6, COLORS.skin.normal], [6, 6, COLORS.face.mouth], [7, 6, COLORS.face.mouth],
  [8, 6, COLORS.skin.normal], [9, 6, COLORS.skin.normal], [10, 6, COLORS.skin.shadow],
  [5, 6, COLORS.face.blush],
  [6, 7, COLORS.skin.shadow], [7, 7, COLORS.skin.normal], [8, 7, COLORS.skin.normal],
  [9, 7, COLORS.skin.shadow], [10, 7, COLORS.armor.blue],
  [6, 8, COLORS.armor.blue], [7, 8, COLORS.armor.blue], [8, 8, COLORS.armor.blue],
  [9, 8, COLORS.armor.blue], [10, 8, COLORS.armor.dark],
  [5, 9, COLORS.armor.dark], [6, 9, COLORS.armor.blue], [7, 9, COLORS.armor.light],
  [8, 9, COLORS.armor.light], [9, 9, COLORS.armor.blue], [10, 9, COLORS.armor.dark],
  [11, 9, COLORS.armor.dark],
  [5, 10, COLORS.armor.blue], [6, 10, COLORS.armor.blue], [7, 10, COLORS.armor.blue],
  [8, 10, COLORS.belt.gold], [9, 10, COLORS.belt.yellow], [10, 10, COLORS.belt.gold],
  [11, 10, COLORS.armor.dark],
  [5, 11, COLORS.armor.blue], [6, 11, COLORS.armor.detail], [7, 11, COLORS.armor.blue],
  [8, 11, COLORS.armor.blue], [9, 11, COLORS.armor.blue], [10, 11, COLORS.armor.dark],
  [4, 12, COLORS.armor.dark], [5, 12, COLORS.armor.blue], [6, 12, COLORS.armor.blue],
  [7, 12, COLORS.armor.light], [8, 12, COLORS.armor.light], [9, 12, COLORS.armor.blue],
  [10, 12, COLORS.armor.blue], [11, 12, COLORS.armor.dark],
  [5, 13, COLORS.belt.dark], [6, 13, COLORS.belt.gold], [7, 13, COLORS.belt.yellow],
  [8, 13, COLORS.belt.yellow], [9, 13, COLORS.belt.gold], [10, 13, COLORS.belt.dark],
  [6, 14, COLORS.leg.dark], [7, 14, COLORS.leg.brown], [8, 14, COLORS.leg.brown],
  [9, 14, COLORS.leg.brown], [10, 14, COLORS.leg.dark],
  [7, 15, COLORS.leg.boot], [8, 15, COLORS.leg.dark], [9, 15, COLORS.leg.dark], [10, 15, COLORS.leg.boot],
  [6, 15, COLORS.leg.dark], [11, 15, COLORS.leg.dark],
  [2, 5, COLORS.sword.silver], [2, 6, COLORS.sword.silver], [2, 7, COLORS.sword.silver],
  [2, 8, COLORS.sword.silver], [2, 9, COLORS.sword.silver], [2, 10, COLORS.sword.silver],
  [3, 5, COLORS.sword.dark], [3, 6, COLORS.sword.gold], [3, 7, COLORS.sword.gold],
  [3, 8, COLORS.sword.gold], [3, 9, COLORS.sword.gold], [3, 10, COLORS.sword.dark],
];

const FACE_RIGHT = [
  [6, 0, COLORS.helmet.darkGold], [7, 0, COLORS.helmet.darkGold], [8, 0, COLORS.helmet.darkGold],
  [9, 0, COLORS.helmet.gold], [10, 0, COLORS.helmet.gold],
  [5, 0, COLORS.helmet.highlight],
  [6, 1, COLORS.helmet.gold], [13, 1, COLORS.helmet.gold], [14, 1, COLORS.feather.red],
  [4, 1, COLORS.feather.orange], [15, 1, COLORS.feather.orange],
  [3, 1, COLORS.feather.yellow], [16, 1, COLORS.feather.yellow],
  [2, 1, COLORS.feather.highlight],
  [5, 2, COLORS.helmet.gold], [6, 2, COLORS.helmet.darkGold], [7, 2, COLORS.helmet.darkGold],
  [8, 2, COLORS.helmet.bronze], [9, 2, COLORS.helmet.bronze], [10, 2, COLORS.helmet.darkGold],
  [11, 2, COLORS.helmet.darkGold], [12, 2, COLORS.helmet.gold],
  [4, 2, COLORS.feather.dark], [13, 2, COLORS.feather.dark],
  [5, 3, COLORS.helmet.gold], [6, 3, COLORS.hair.brown], [7, 3, COLORS.hair.dark],
  [8, 3, COLORS.hair.dark], [9, 3, COLORS.hair.brown], [10, 3, COLORS.hair.brown],
  [11, 3, COLORS.helmet.darkGold], [12, 3, COLORS.hair.brown],
  [4, 3, COLORS.feather.highlight], [13, 3, COLORS.feather.highlight],
  [6, 4, COLORS.helmet.gold], [7, 4, COLORS.skin.shadow], [8, 4, COLORS.skin.normal],
  [9, 4, COLORS.skin.normal], [10, 4, COLORS.skin.normal], [11, 4, COLORS.skin.light],
  [12, 4, COLORS.hair.light],
  [7, 5, COLORS.skin.normal], [8, 5, COLORS.skin.normal], [9, 5, COLORS.skin.normal],
  [10, 5, COLORS.skin.normal], [11, 5, COLORS.face.eye], [12, 5, COLORS.skin.normal],
  [11, 5, COLORS.face.brow], [12, 5, COLORS.face.brow],
  [7, 6, COLORS.skin.shadow], [8, 6, COLORS.skin.normal], [9, 6, COLORS.face.mouth],
  [10, 6, COLORS.face.mouth], [11, 6, COLORS.skin.normal], [12, 6, COLORS.skin.normal],
  [12, 6, COLORS.face.blush],
  [7, 7, COLORS.armor.blue], [8, 7, COLORS.skin.shadow], [9, 7, COLORS.skin.normal],
  [10, 7, COLORS.skin.normal], [11, 7, COLORS.skin.shadow],
  [7, 8, COLORS.armor.dark], [8, 8, COLORS.armor.blue], [9, 8, COLORS.armor.blue],
  [10, 8, COLORS.armor.blue], [11, 8, COLORS.armor.blue],
  [7, 9, COLORS.armor.dark], [8, 9, COLORS.armor.blue], [9, 9, COLORS.armor.light],
  [10, 9, COLORS.armor.light], [11, 9, COLORS.armor.blue], [12, 9, COLORS.armor.dark],
  [7, 10, COLORS.armor.dark], [8, 10, COLORS.belt.gold], [9, 10, COLORS.belt.yellow],
  [10, 10, COLORS.belt.gold], [11, 10, COLORS.armor.blue], [12, 10, COLORS.armor.blue],
  [7, 11, COLORS.armor.dark], [8, 11, COLORS.armor.blue], [9, 11, COLORS.armor.blue],
  [10, 11, COLORS.armor.detail], [11, 11, COLORS.armor.blue], [12, 11, COLORS.armor.blue],
  [7, 12, COLORS.armor.blue], [8, 12, COLORS.armor.light], [9, 12, COLORS.armor.light],
  [10, 12, COLORS.armor.blue], [11, 12, COLORS.armor.blue], [12, 12, COLORS.armor.dark],
  [7, 13, COLORS.belt.gold], [8, 13, COLORS.belt.yellow], [9, 13, COLORS.belt.yellow],
  [10, 13, COLORS.belt.gold], [11, 13, COLORS.belt.dark], [12, 13, COLORS.belt.dark],
  [7, 14, COLORS.leg.dark], [8, 14, COLORS.leg.brown], [9, 14, COLORS.leg.brown],
  [10, 14, COLORS.leg.brown], [11, 14, COLORS.leg.dark],
  [7, 15, COLORS.leg.dark], [8, 15, COLORS.leg.boot], [9, 15, COLORS.leg.dark], [10, 15, COLORS.leg.dark], [11, 15, COLORS.leg.boot],
  [15, 6, COLORS.shield.blue], [15, 7, COLORS.shield.blue], [15, 8, COLORS.shield.blue],
  [15, 9, COLORS.shield.blue], [15, 10, COLORS.shield.blue],
  [16, 6, COLORS.shield.highlight], [16, 7, COLORS.shield.gold], [16, 8, COLORS.shield.gold],
  [16, 9, COLORS.shield.highlight], [16, 10, COLORS.shield.highlight],
  [17, 6, COLORS.shield.dark], [17, 7, COLORS.shield.blue], [17, 8, COLORS.shield.blue],
  [17, 9, COLORS.shield.dark], [17, 10, COLORS.shield.dark],
];

const IDLE_FRAMES = [
  [
    { pixels: [
      [7, 14, COLORS.leg.dark], [8, 14, COLORS.leg.brown], [9, 14, COLORS.leg.brown], [10, 14, COLORS.leg.brown], [11, 14, COLORS.leg.dark],
      [2, 1, COLORS.feather.yellow], [16, 1, COLORS.feather.yellow],
    ] }
  ],
  [
    { pixels: [
      [7, 14, COLORS.leg.dark], [8, 14, COLORS.leg.dark], [9, 14, COLORS.leg.dark], [10, 14, COLORS.leg.dark], [11, 14, COLORS.leg.dark],
      [2, 1, COLORS.feather.orange], [16, 1, COLORS.feather.orange],
    ] }
  ],
  [
    { pixels: [
      [7, 14, COLORS.leg.dark], [8, 14, COLORS.leg.brown], [9, 14, COLORS.leg.brown], [10, 14, COLORS.leg.brown], [11, 14, COLORS.leg.dark],
      [3, 1, COLORS.feather.yellow], [15, 1, COLORS.feather.yellow],
    ] }
  ],
];

const WALK_FRAMES = [
  [
    { pixels: [
      [6, 14, COLORS.leg.dark], [7, 14, COLORS.leg.brown], [8, 14, COLORS.leg.brown], [9, 14, COLORS.leg.dark], [10, 14, COLORS.leg.dark],
      [7, 15, COLORS.leg.dark], [8, 15, COLORS.leg.boot], [9, 15, COLORS.leg.dark],
    ] }
  ],
  [
    { pixels: [
      [7, 14, COLORS.leg.dark], [8, 14, COLORS.leg.brown], [9, 14, COLORS.leg.brown], [10, 14, COLORS.leg.brown], [11, 14, COLORS.leg.dark],
      [7, 15, COLORS.leg.boot], [8, 15, COLORS.leg.dark], [9, 15, COLORS.leg.dark], [10, 15, COLORS.leg.boot],
    ] }
  ],
  [
    { pixels: [
      [6, 14, COLORS.leg.dark], [7, 14, COLORS.leg.dark], [8, 14, COLORS.leg.brown], [9, 14, COLORS.leg.brown], [10, 14, COLORS.leg.brown], [11, 14, COLORS.leg.dark],
      [8, 15, COLORS.leg.dark], [9, 15, COLORS.leg.boot], [10, 15, COLORS.leg.dark], [11, 15, COLORS.leg.boot],
    ] }
  ],
  [
    { pixels: [
      [7, 14, COLORS.leg.dark], [8, 14, COLORS.leg.brown], [9, 14, COLORS.leg.brown], [10, 14, COLORS.leg.brown], [11, 14, COLORS.leg.dark],
      [7, 15, COLORS.leg.boot], [8, 15, COLORS.leg.dark], [9, 15, COLORS.leg.dark], [10, 15, COLORS.leg.boot],
    ] }
  ],
];

export const drawPlayer = (ctx, currentUnit) => drawUnit(ctx, currentUnit, {
  down: FACE_DOWN,
  up: FACE_UP,
  left: FACE_LEFT,
  right: FACE_RIGHT,
  walk: WALK_FRAMES,
  idle: IDLE_FRAMES,
})

export const drawPlayerAvatar = (ctx, currentUnit, avatarPos) => drawAvatar(ctx, currentUnit, avatarPos, PLAYER_AVATAR)
